-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here\\wsl.localhost\Ubuntu-22.04\home\heyyshaarib\.config\nvim\lua\plugins\colorscheme.lua\\wsl.localhost\Ubuntu-22.04\home\heyyshaarib\.config\nvim\lua\plugns\colorscheme.lua
